name: Croggle
markdown: redcarpet
highlighter: pygments
github: [Repository metadata]
paginate: 5
gems: ['jekyll-less']

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
